title: Xinyuan Cheng
first_name: Xinyuan
last_name: Cheng
email: Xinyuan.Cheng@campus.lmu.de
description: Master's student in Computational Linguistics at LMU Munich
url: "https://noah-13.github.io"
baseurl: ""
